// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTodAF5hDVpVotudoPk37VJ-38RHgVyQk',
    appId: '1:684815401544:web:25c32cb921a50a6513ce7d',
    messagingSenderId: '684815401544',
    projectId: 'magicnote-b0889',
    authDomain: 'magicnote-b0889.firebaseapp.com',
    storageBucket: 'magicnote-b0889.appspot.com',
    measurementId: 'G-2CX87CB8EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfqDPDIdA459yIIXzPDBFGOreDH9S7iGk',
    appId: '1:684815401544:android:0eaa1010d37b3f2d13ce7d',
    messagingSenderId: '684815401544',
    projectId: 'magicnote-b0889',
    storageBucket: 'magicnote-b0889.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyoFYi3J_RniILk72fgNHTmhbictKpxww',
    appId: '1:684815401544:ios:1b313ab742df34b413ce7d',
    messagingSenderId: '684815401544',
    projectId: 'magicnote-b0889',
    storageBucket: 'magicnote-b0889.appspot.com',
    iosBundleId: 'com.wondapro.magicnote2024.magicNote',
  );

}